# The URL the site will be built for
base_url = "https://zjayv.com"
title = "Zach Valenta"
description = "notes on books"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[markdown]
# Syntax highlighting configuration
[markdown.highlighting]
theme = "catppuccin-mocha"
style = "inline"

[extra]
# Put all your custom variables here
